# Generated by Django 4.2.17 on 2025-01-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('name',)},
        ),
    ]
