# Generated by Django 4.2.17 on 2025-01-27 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadfile',
            old_name='content',
            new_name='file',
        ),
    ]
